import archiver from 'archiver';
import { Readable } from 'stream';

class ZipService {
  
  async createProjectZip(projectData) {
    try {
      console.log('📦 Creating ZIP file...');

      return new Promise((resolve, reject) => {
        const archive = archiver('zip', {
          zlib: { level: 9 }
        });

        const chunks = [];

        archive.on('data', (chunk) => {
          chunks.push(chunk);
        });

        archive.on('end', () => {
          const buffer = Buffer.concat(chunks);
          console.log('✅ ZIP created:', buffer.length, 'bytes');
          resolve(buffer);
        });

        archive.on('error', (err) => {
          console.error('❌ ZIP error:', err);
          reject(err);
        });

        // Add files to archive
        const files = projectData.files;
        
        for (const [filePath, content] of Object.entries(files)) {
          archive.append(content, { name: filePath });
        }

        // Add README if not present
        if (!files['README.md']) {
          const readme = `# ${projectData.projectName}\n\nGenerated by Chlorophy AI\n\n## Setup\n\n1. Extract this ZIP\n2. Open index.html in browser\n3. Enjoy!\n`;
          archive.append(readme, { name: 'README.md' });
        }

        archive.finalize();
      });

    } catch (error) {
      console.error('❌ ZIP service error:', error);
      throw error;
    }
  }
}

export default new ZipService();